version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
      POSTGRES_PASSWORD: "Keid11HPsAE6SrknQ9UXoZUg8udZKieA"
    volumes:
      - todo_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "bVNk-vYPNJuaSm39rcB4mssTT80QgAmD"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  todo_data:
